### ISSUE TITLE
Create install task

### ISSUE THREAD

**Issue by Johann-S** [Strikesoft/Downloader#31]
Install task  will : 

- [ ] Check `php` command
- [ ] Download composer
- [ ] Install vendors
- [ ] Copy `config/param.yml.dist` to `config/param.yml`
- [ ] Run `bundle-prod` and `bundle-dev`

And voilà
